# Generated by Django 2.1.4 on 2018-12-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeview', '0002_auto_20181225_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
