# Generated by Django 2.1.4 on 2018-12-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeview', '0005_auto_20181230_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
