# Generated by Django 2.1.4 on 2018-12-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='buy_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='marked_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trans',
            name='no_of_items',
            field=models.IntegerField(null=True),
        ),
    ]
