# Generated by Django 2.1.4 on 2018-12-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeview', '0004_auto_20181225_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./images'),
        ),
    ]
